AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/*'
    - 'Gemfile.lock'
    - 'vendor/**/*.rb'
  NewCops: disable

require: rubocop-rspec

Metrics/BlockNesting:
  Max: 5

Style/AsciiComments:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLinesAroundBeginBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/InheritException:
  EnforcedStyle: standard_error

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames: _

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

RSpec/BeEql:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/Focus:
  Enabled: true

RSpec/ImplicitSubject:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/PredicateMatcher:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FloatDivision:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
