inherit_from:
  - .rubocop_todo.yml
  - .rubocop_base.yml

RSpec/FilePath:
  CustomTransform:
    OpenAI: openai
    OpenAIBot: openai_bot
    OpenAITool: openai_tool
    OpenAIChatBot: openai_chat_bot
    OpenAIChatTool: openai_chat_tool
